// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPXAPEbmT0UxJYOJaCGG3Xjcy5cDEatag',
    appId: '1:934600334709:web:b0c8afbb8ec4bac537873c',
    messagingSenderId: '934600334709',
    projectId: 'backyard-presence-x',
    authDomain: 'backyard-presence-x.firebaseapp.com',
    storageBucket: 'backyard-presence-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLmg8nwjQTr7F9UHZEJgVJb3L10HUg5s',
    appId: '1:934600334709:android:8355fee8edadaa1837873c',
    messagingSenderId: '934600334709',
    projectId: 'backyard-presence-x',
    storageBucket: 'backyard-presence-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwH1mTyOmnPP0ShhQnaduPleWnDcr2zmw',
    appId: '1:934600334709:ios:3d20dfd2dc25bc3837873c',
    messagingSenderId: '934600334709',
    projectId: 'backyard-presence-x',
    storageBucket: 'backyard-presence-x.appspot.com',
    iosBundleId: 'com.bagasyudhistira.presence',
  );
}
